### ISSUE TITLE
protobuf requires Python '>=3.7' but the running Python is 3.6.9

### ISSUE THREAD

**Issue by abusm4n** [sss-wue/scraps#2]
Hello there,
thank you for sharing.
I tried to run the Blockchain experiment but it's fails when running  _~$ docker-compose -f test.yml up_
Tried uncommenting  line 209-213 in _test.tml_ file didn't work.
Kindly see screenshot attached.

Any suggestion? thanks again.

![Screenshot from 2022-05-30 13-40-10](https://user-images.githubusercontent.com/39135208/170986665-7c6de87a-0671-41f4-bea3-7abefb37b346.png)

**Comment by AlaBYahya** [comment]
Issue was caused by new version of protobuf. It is now solved. 
Thanks for reporting.
